//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sandigital.sharepoint.webparts.PainelOperador {
    using DevExpress.Web.ASPxEditors;
    using System.Web.Security;
    using DevExpress.Web.ASPxGridView;
    using System.Web.UI.WebControls;
    using System.Web;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using DevExpress.Web.ASPxTimer;
    using System.Web.UI;
    using System.Web.UI.HtmlControls;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint;
    using System.Configuration;
    using System;
    using System.Text;
    using System.Web.Profile;
    using System.Web.Caching;
    using System.Collections;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.Collections.Specialized;
    using System.Web.SessionState;
    
    
    public partial class PainelOperador {
        
        protected global::System.Web.UI.WebControls.Label lblErro;
        
        protected global::System.Web.UI.WebControls.HiddenField HField;
        
        protected global::System.Web.UI.Timer TAtualizaGrids;
        
        protected global::DevExpress.Web.ASPxEditors.ASPxButton btnStatusOperador;
        
        protected global::DevExpress.Web.ASPxGridView.ASPxGridView dGridMain;
        
        protected global::DevExpress.Web.ASPxGridView.ASPxGridView dGridMainMeusAtend;
        
        protected global::DevExpress.Web.ASPxTimer.ASPxTimer tAtualiza;
        
        protected global::System.Web.UI.WebControls.HiddenField HField2;
        
        public static implicit operator global::System.Web.UI.TemplateControl(PainelOperador target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblErro() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblErro = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblErro";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlHField() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.HField = @__ctrl;
            @__ctrl.ID = "HField";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.Timer @__BuildControlTAtualizaGrids() {
            global::System.Web.UI.Timer @__ctrl;
            @__ctrl = new global::System.Web.UI.Timer();
            this.TAtualizaGrids = @__ctrl;
            @__ctrl.ID = "TAtualizaGrids";
            @__ctrl.Interval = 5000;
            @__ctrl.Enabled = false;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        "));
            @__ctrl.Tick -= new System.EventHandler<System.EventArgs>(this.TAtualizaGrids_Tick);
            @__ctrl.Tick += new System.EventHandler<System.EventArgs>(this.TAtualizaGrids_Tick);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxEditors.ASPxButton @__BuildControlbtnStatusOperador() {
            global::DevExpress.Web.ASPxEditors.ASPxButton @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxEditors.ASPxButton();
            this.btnStatusOperador = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ApplyStyleSheetThemeInternal();
            @__ctrl.ID = "btnStatusOperador";
            @__ctrl.Text = "Online";
            @__ctrl.Click -= new System.EventHandler(this.btnStatusOperador_Click);
            @__ctrl.Click += new System.EventHandler(this.btnStatusOperador_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control2(DevExpress.Web.ASPxGridView.ASPxGridViewLoadingPanelSettings @__ctrl) {
            @__ctrl.ShowImage = false;
            @__ctrl.Text = "Carregando&hellip;";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control4(DevExpress.Web.ASPxPager.AllButtonProperties @__ctrl) {
            @__ctrl.Text = "All";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control5(DevExpress.Web.ASPxPager.NextButtonProperties @__ctrl) {
            @__ctrl.Text = "Next >";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control6(DevExpress.Web.ASPxPager.PrevButtonProperties @__ctrl) {
            @__ctrl.Text = "< Prev";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control3(DevExpress.Web.ASPxGridView.ASPxGridViewPagerSettings @__ctrl) {
            @__ctrl.ShowDefaultImages = false;
            this.@__BuildControl__control4(@__ctrl.AllButton);
            this.@__BuildControl__control5(@__ctrl.NextPageButton);
            this.@__BuildControl__control6(@__ctrl.PrevPageButton);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control7(DevExpress.Web.ASPxGridView.ASPxGridViewTextSettings @__ctrl) {
            @__ctrl.EmptyDataRow = "Não há registros para a consulta.";
            @__ctrl.GroupPanel = "Atendimentos Pedentes";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control10(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                                            <table>
                                                                <tr>
                                                                    <td> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </td>
                                                                </tr>
                                                            </table>
                                                        "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control9() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.DataItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control10));
            @__ctrl.Caption = " ";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(220, System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.VisibleIndex = 0;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control11() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.Caption = "Noc";
            @__ctrl.FieldName = "Noc";
            @__ctrl.VisibleIndex = 1;
            @__ctrl.GroupIndex = 0;
            @__ctrl.SortIndex = 0;
            @__ctrl.SortOrder = DevExpress.Data.ColumnSortOrder.Ascending;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control13(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Left;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control12() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.FieldName = "Usuario";
            @__ctrl.Caption = "Usuário";
            @__ctrl.VisibleIndex = 2;
            this.@__BuildControl__control13(@__ctrl.CellStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control15(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Center;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataDateColumn @__BuildControl__control14() {
            global::DevExpress.Web.ASPxGridView.GridViewDataDateColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataDateColumn();
            @__ctrl.FieldName = "dt_inicio";
            @__ctrl.Caption = "data de Inicio";
            @__ctrl.VisibleIndex = 3;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100, System.Web.UI.WebControls.UnitType.Pixel);
            this.@__BuildControl__control15(@__ctrl.CellStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__control18() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(2, 1);
            @__ctrl.TemplateControl = this;
            @__ctrl.SetStaticString(0, "\r\n                                                               <a href=\"javascr" +
                    "ipt:void(0);\" onclick=\'PassarParaMeusAtendimentos(&#039;");
            @__ctrl.SetStaticString(1, "&#039;)\'>Abrir</a>\r\n                                                           ");
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__control18);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public void @__DataBind__control18(object sender, System.EventArgs e) {
            DevExpress.Web.ASPxGridView.GridViewDataItemTemplateContainer Container;
            System.Web.UI.DataBoundLiteralControl target;
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            Container = ((DevExpress.Web.ASPxGridView.GridViewDataItemTemplateContainer)(target.BindingContainer));
            target.SetDataBoundString(0, System.Convert.ToString(Container.KeyValue, System.Globalization.CultureInfo.CurrentCulture));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control17(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control18();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control19(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Center;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control16() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.DataItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control17));
            @__ctrl.Caption = "Ações";
            @__ctrl.VisibleIndex = 4;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(80, System.Web.UI.WebControls.UnitType.Pixel);
            this.@__BuildControl__control19(@__ctrl.CellStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control8(DevExpress.Web.ASPxGridView.GridViewColumnCollection @__ctrl) {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control9();
            @__ctrl.Add(@__ctrl1);
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control11();
            @__ctrl.Add(@__ctrl2);
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control12();
            @__ctrl.Add(@__ctrl3);
            global::DevExpress.Web.ASPxGridView.GridViewDataDateColumn @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control14();
            @__ctrl.Add(@__ctrl4);
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl5;
            @__ctrl5 = this.@__BuildControl__control16();
            @__ctrl.Add(@__ctrl5);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control21(DevExpress.Web.ASPxEditors.ProgressBarStyle @__ctrl) {
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(25, System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control20(DevExpress.Web.ASPxGridView.GridViewEditorStyles @__ctrl) {
            this.@__BuildControl__control21(@__ctrl.ProgressBar);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.ASPxGridView @__BuildControldGridMain() {
            global::DevExpress.Web.ASPxGridView.ASPxGridView @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.ASPxGridView();
            this.dGridMain = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ApplyStyleSheetThemeInternal();
            @__ctrl.ID = "dGridMain";
            @__ctrl.KeyFieldName = "id_atendimento";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(740, System.Web.UI.WebControls.UnitType.Pixel);
            this.@__BuildControl__control2(@__ctrl.SettingsLoadingPanel);
            this.@__BuildControl__control3(@__ctrl.SettingsPager);
            this.@__BuildControl__control7(@__ctrl.SettingsText);
            this.@__BuildControl__control8(@__ctrl.Columns);
            this.@__BuildControl__control20(@__ctrl.StylesEditors);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control23(DevExpress.Web.ASPxPager.AllButtonProperties @__ctrl) {
            @__ctrl.Text = "All";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control24(DevExpress.Web.ASPxPager.NextButtonProperties @__ctrl) {
            @__ctrl.Text = "Next >";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control25(DevExpress.Web.ASPxPager.PrevButtonProperties @__ctrl) {
            @__ctrl.Text = "< Prev";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control22(DevExpress.Web.ASPxGridView.ASPxGridViewPagerSettings @__ctrl) {
            @__ctrl.ShowDefaultImages = false;
            this.@__BuildControl__control23(@__ctrl.AllButton);
            this.@__BuildControl__control24(@__ctrl.NextPageButton);
            this.@__BuildControl__control25(@__ctrl.PrevPageButton);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control26(DevExpress.Web.ASPxGridView.ASPxGridViewTextSettings @__ctrl) {
            @__ctrl.EmptyDataRow = "Não há registros para a consulta.";
            @__ctrl.GroupPanel = "Meus Atendimentos";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control28() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.Caption = "Noc";
            @__ctrl.FieldName = "Noc";
            @__ctrl.VisibleIndex = 0;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control30(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Center;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control29() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.Caption = "Data do Inicio";
            @__ctrl.FieldName = "dt_inicio";
            @__ctrl.VisibleIndex = 2;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(80, System.Web.UI.WebControls.UnitType.Pixel);
            this.@__BuildControl__control30(@__ctrl.CellStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control32(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Center;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control31() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.Caption = "Data do Fim";
            @__ctrl.FieldName = "dt_fim";
            @__ctrl.VisibleIndex = 3;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(80, System.Web.UI.WebControls.UnitType.Pixel);
            this.@__BuildControl__control32(@__ctrl.CellStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control34(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Center;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control33() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.Caption = "Mensagens";
            @__ctrl.FieldName = "Mensagens";
            @__ctrl.VisibleIndex = 4;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(80, System.Web.UI.WebControls.UnitType.Pixel);
            this.@__BuildControl__control34(@__ctrl.CellStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control36(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Center;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control35() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.Caption = "Status";
            @__ctrl.FieldName = "Status";
            @__ctrl.VisibleIndex = 5;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(80, System.Web.UI.WebControls.UnitType.Pixel);
            this.@__BuildControl__control36(@__ctrl.CellStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__control39() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(2, 1);
            @__ctrl.TemplateControl = this;
            @__ctrl.SetStaticString(0, "\r\n                                                                    <a href=\"ja" +
                    "vascript:void(0);\" onclick=\'ShowWindow(&#039; /EbtChat/PopupOperador(&#039;,&#03" +
                    "9;");
            @__ctrl.SetStaticString(1, "&#039;)\'>Exibir</a>\r\n                                                            " +
                    "   ");
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__control39);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public void @__DataBind__control39(object sender, System.EventArgs e) {
            DevExpress.Web.ASPxGridView.GridViewDataItemTemplateContainer Container;
            System.Web.UI.DataBoundLiteralControl target;
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            Container = ((DevExpress.Web.ASPxGridView.GridViewDataItemTemplateContainer)(target.BindingContainer));
            target.SetDataBoundString(0, System.Convert.ToString(Container.KeyValue, System.Globalization.CultureInfo.CurrentCulture));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control38(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control39();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control40(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Center;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control37() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.DataItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control38));
            @__ctrl.Caption = "Ações";
            @__ctrl.VisibleIndex = 6;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(60, System.Web.UI.WebControls.UnitType.Pixel);
            this.@__BuildControl__control40(@__ctrl.CellStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control27(DevExpress.Web.ASPxGridView.GridViewColumnCollection @__ctrl) {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control28();
            @__ctrl.Add(@__ctrl1);
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control29();
            @__ctrl.Add(@__ctrl2);
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control31();
            @__ctrl.Add(@__ctrl3);
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control33();
            @__ctrl.Add(@__ctrl4);
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl5;
            @__ctrl5 = this.@__BuildControl__control35();
            @__ctrl.Add(@__ctrl5);
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl6;
            @__ctrl6 = this.@__BuildControl__control37();
            @__ctrl.Add(@__ctrl6);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control41(DevExpress.Web.ASPxGridView.ASPxGridViewSettings @__ctrl) {
            @__ctrl.ShowGroupPanel = true;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control43(DevExpress.Web.ASPxEditors.ProgressBarStyle @__ctrl) {
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(25, System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control42(DevExpress.Web.ASPxGridView.GridViewEditorStyles @__ctrl) {
            this.@__BuildControl__control43(@__ctrl.ProgressBar);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.ASPxGridView @__BuildControldGridMainMeusAtend() {
            global::DevExpress.Web.ASPxGridView.ASPxGridView @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.ASPxGridView();
            this.dGridMainMeusAtend = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ApplyStyleSheetThemeInternal();
            @__ctrl.ID = "dGridMainMeusAtend";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.KeyFieldName = "id_atendimento";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(740, System.Web.UI.WebControls.UnitType.Pixel);
            this.@__BuildControl__control22(@__ctrl.SettingsPager);
            this.@__BuildControl__control26(@__ctrl.SettingsText);
            this.@__BuildControl__control27(@__ctrl.Columns);
            this.@__BuildControl__control41(@__ctrl.Settings);
            this.@__BuildControl__control42(@__ctrl.StylesEditors);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control44(DevExpress.Web.ASPxTimer.TimerClientSideEvents @__ctrl) {
            @__ctrl.Tick = "function(s, e) {\r\n\tAlertaVisual(s,e);\r\n}";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxTimer.ASPxTimer @__BuildControltAtualiza() {
            global::DevExpress.Web.ASPxTimer.ASPxTimer @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxTimer.ASPxTimer();
            this.tAtualiza = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ApplyStyleSheetThemeInternal();
            @__ctrl.ID = "tAtualiza";
            @__ctrl.ClientInstanceName = "tAtualiza";
            @__ctrl.Interval = 5000;
            @__ctrl.Enabled = true;
            this.@__BuildControl__control44(@__ctrl.ClientSideEvents);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlHField2() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.HField2 = @__ctrl;
            @__ctrl.ID = "HField2";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::com.sandigital.sharepoint.webparts.PainelOperador.PainelOperador @__ctrl) {
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllblErro();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.HiddenField @__ctrl2;
            @__ctrl2 = this.@__BuildControlHField();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.Timer @__ctrl3;
            @__ctrl3 = this.@__BuildControlTAtualizaGrids();
            @__parser.AddParsedSubObject(@__ctrl3);
            global::DevExpress.Web.ASPxEditors.ASPxButton @__ctrl4;
            @__ctrl4 = this.@__BuildControlbtnStatusOperador();
            @__parser.AddParsedSubObject(@__ctrl4);
            global::DevExpress.Web.ASPxGridView.ASPxGridView @__ctrl5;
            @__ctrl5 = this.@__BuildControldGridMain();
            @__parser.AddParsedSubObject(@__ctrl5);
            global::DevExpress.Web.ASPxGridView.ASPxGridView @__ctrl6;
            @__ctrl6 = this.@__BuildControldGridMainMeusAtend();
            @__parser.AddParsedSubObject(@__ctrl6);
            global::DevExpress.Web.ASPxTimer.ASPxTimer @__ctrl7;
            @__ctrl7 = this.@__BuildControltAtualiza();
            @__parser.AddParsedSubObject(@__ctrl7);
            global::System.Web.UI.WebControls.HiddenField @__ctrl8;
            @__ctrl8 = this.@__BuildControlHField2();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n\r\n\r\n\r\n<script type=\"text/javascript\" >\r\n\r\n    function ShowWindow(url, keyValue" +
                    ") {\r\n        var HField = document.getElementById(\"");
                                      @__w.Write( HField.UniqueID );

            @__w.Write(@""");
        if (HField.value == 1) {
            window.open(url + '?id=' + keyValue, ""janela"" + keyValue, ""width=650,height=350,scrollbars=NO"")
        }
        else { alert('Para executar esta operação o operador deverá estar Online!'); }
    }

    function PassarParaMeusAtendimentos(keyValue) {

        var HField = document.getElementById(""");
                                      @__w.Write( HField.UniqueID );

            @__w.Write(@""");
        if (HField.value == 1) {
            if (!confirm(""Deseja realmente abrir este Chat?""))
                return false;
            else {
                __doPostBack('MeusAtendimentos', keyValue);
            }
        }
        else { alert('Para executar esta opera;áo o operador deverá estar Online!'); }
    }


    function AlertaVisual(s, e) {

        var hf = document.getElementById(""");
                                  @__w.Write( HField2.UniqueID );

            @__w.Write(@""");
        if (hf.value > 0)
            self.focus();
    }



</script>
<style type=""text/css"" >

 body
    {
        font: 11px Tahoma,Arial,Helvetiva,sans-serif;
    }
    
.logo_chat
{
    width:100%;
   /* background-image:url('/img/fundoChat.jpg'); 
    background-repeat:repeat-x;   */
 /*   background-color:#6188A9;
    height:50px;
    padding-right:20px;*/
}

.tituloPainel
{
    /*vertical-align:middle;   
    font-weight:bold;    
    color:White;*/    
    width:100%;    
    /*height:50px;
    padding-left:20px;*/
}


#titulo_painel{
	
	vertical-align:middle;   
    font-weight:bold;    
   color:White;
    width:740px; 
    text-align:left;
	height:25px;

}

</style>

");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write(" \r\n\r\n<div style=\"width:100%;margin:0;padding:0;background:#dedfde;padding-left:10" +
                    "px;padding-top:10px\">       \r\n    \r\n\r\n\r\n\r\n        ");
            parameterContainer.Controls[1].RenderControl(@__w);
            @__w.Write("\r\n        ");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n\r\n\r\n\r\n\r\n            <table cellpadding=\"0\" cellspacing=\"0\" style=\"width:100%;\" " +
                    ">\r\n                <tr valign=\"top\">\r\n                    <td align=\"left\">     " +
                    "           \r\n                        <table width=\"100%;\" cellpadding=\"0\" cellsp" +
                    "acing=\"0\">                   \r\n                            <tr valign=\"top\">\r\n  " +
                    "                              <td align=\"left\" >                \r\n              " +
                    "                      <table cellpadding=\"0\" cellspacing=\"0\" style=\"width:100%\" " +
                    ">\r\n                                        <tr valign=\"top\">\r\n                  " +
                    "                          <td align=\"left\"  > \r\n                                " +
                    "            <div id=\"titulo_painel\">\r\n                                          " +
                    "  <table cellpadding=\"0\" cellspacing=\"0\" style=\"width:100%;height:25px;\" >\r\n    " +
                    "                                            <tr>\r\n                              " +
                    "                      <td align=\"left\" style=\"padding-left:20px;\" >             " +
                    "                                                                         \r\n     " +
                    "                                                <p style=\"font-size:17px;color:W" +
                    "hite;\">   Painel de Controle Operador</p>                                       " +
                    "      \r\n                                                    </td>\r\n             " +
                    "                                       <td style=\"width:130px;\"><b> <span style=" +
                    "\"color:White;font-size:small;\">Meu Status:</span>  </b></td>\r\n                  " +
                    "                                  <td style=\"width:90px;padding-right:10px\">\r\n\r\n" +
                    "\r\n                                                        ");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("   \r\n                                                        \r\n                  " +
                    "                                      \r\n                                        " +
                    "                                                              \r\n                " +
                    "                                    </td>\r\n                                     " +
                    "           </tr>\r\n                                            </table>          " +
                    "                         \r\n                                                </div" +
                    ">                                                                           \r\n  " +
                    "                                          </td>\r\n                               " +
                    "         </tr>       \r\n                                        <tr valign=\"top\">" +
                    "\r\n                                            <td align=\"left\" >\r\n              " +
                    "                                  <table class=\"dxgvControl_PlasticBlue\" cellspa" +
                    "cing=\"0\" cellpadding=\"0\" id=\"clt_NOCOperador1_dGridMainStatusNoc\" border=\"0\" sty" +
                    "le=\"width:740px;border-collapse:collapse;border-collapse:separate;\">\r\n\t         " +
                    "                                       <tr>\r\n\t\t                                 " +
                    "               <td>\r\n                                                           " +
                    " <div id=\"clt_NOCOperador1_dGridMainMeusAtend_DXTDgrouppanel\" class=\"bg-primary\"" +
                    ">\r\n\t\t\t                                                    Atendimentos Pedentes\r" +
                    "\n\t\t                                                    </div>\r\n\t\t               " +
                    "                                 </td>\r\n\t\t                                      " +
                    "      </tr>\r\n\t\t                                        </table>\r\n               " +
                    "                                 ");
            parameterContainer.Controls[4].RenderControl(@__w);
            @__w.Write(@"
                                            </td>
                                        </tr>                    
                                    </table>                          
                                </td>
                            </tr>      
                            <tr valign=""top"">
                                <td align=""left"" style=""padding-top:20px"" >                
                                    <table width=""100%"" cellpadding=""0"" cellspacing=""0"">
                                        <tr valign=""top"">
                                            <td align=""left"" >
                                            </td>
                                        </tr>       
                                        <tr valign=""top"">
                                            <td align=""left"" >
                                                ");
            parameterContainer.Controls[5].RenderControl(@__w);
            @__w.Write(@"
                                            </td>
                                        </tr>                    
                                    </table>                          
                                </td>
                            </tr>                                
                        </table>                                                       
                    </td>
                </tr>       
            </table>
       
       
    
    
</div>
 


 

");
            parameterContainer.Controls[6].RenderControl(@__w);
            @__w.Write("\r\n\r\n\r\n\r\n\r\n \r\n        ");
            parameterContainer.Controls[7].RenderControl(@__w);
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
