#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sandigital.sharepoint.dal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GIR")]
	public partial class _GirGrdDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public _GirGrdDataContext() : 
				base("Data Source=localhost;Initial Catalog=Eventos;Integrated Security=True", mappingSource)
		{
			OnCreated();
		}
		
		public _GirGrdDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _GirGrdDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _GirGrdDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _GirGrdDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NS_vwPortal> NS_vwPortal
		{
			get
			{
				return this.GetTable<NS_vwPortal>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NS_vwPortal")]
	public partial class NS_vwPortal
	{
		
		private int _SGIR;
		
		private string _Grd;
		
		private string _Status;
		
		private System.Nullable<System.DateTime> _Inicio;
		
		private string _Tipo;
		
		private string _Rede;
		
		private string _Atividade;
		
		private System.Nullable<bool> _Interrupcao;
		
		private System.Nullable<bool> _Net;
		
		private System.Nullable<bool> _Claro;
		
		private System.Nullable<bool> _Gir;
		
		private string _Localidade;
		
		public NS_vwPortal()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGIR", DbType="Int NOT NULL")]
		public int SGIR
		{
			get
			{
				return this._SGIR;
			}
			set
			{
				if ((this._SGIR != value))
				{
					this._SGIR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grd", DbType="VarChar(50)")]
		public string Grd
		{
			get
			{
				return this._Grd;
			}
			set
			{
				if ((this._Grd != value))
				{
					this._Grd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(25)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inicio", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Inicio
		{
			get
			{
				return this._Inicio;
			}
			set
			{
				if ((this._Inicio != value))
				{
					this._Inicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="Char(20)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rede", DbType="VarChar(50)")]
		public string Rede
		{
			get
			{
				return this._Rede;
			}
			set
			{
				if ((this._Rede != value))
				{
					this._Rede = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Atividade", DbType="VarChar(100)")]
		public string Atividade
		{
			get
			{
				return this._Atividade;
			}
			set
			{
				if ((this._Atividade != value))
				{
					this._Atividade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Interrupcao", DbType="Bit")]
		public System.Nullable<bool> Interrupcao
		{
			get
			{
				return this._Interrupcao;
			}
			set
			{
				if ((this._Interrupcao != value))
				{
					this._Interrupcao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Net", DbType="Bit")]
		public System.Nullable<bool> Net
		{
			get
			{
				return this._Net;
			}
			set
			{
				if ((this._Net != value))
				{
					this._Net = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Claro", DbType="Bit")]
		public System.Nullable<bool> Claro
		{
			get
			{
				return this._Claro;
			}
			set
			{
				if ((this._Claro != value))
				{
					this._Claro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gir", DbType="Bit")]
		public System.Nullable<bool> Gir
		{
			get
			{
				return this._Gir;
			}
			set
			{
				if ((this._Gir != value))
				{
					this._Gir = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Localidade", DbType="VarChar(120)")]
		public string Localidade
		{
			get
			{
				return this._Localidade;
			}
			set
			{
				if ((this._Localidade != value))
				{
					this._Localidade = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
