//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sandigital.sharepoint.webparts.ParticipantesReuniao {
    using DevExpress.Web.ASPxEditors;
    using System.Web.Security;
    using DevExpress.Web.ASPxGridView;
    using System.Web.UI.WebControls;
    using System.Web;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Web.UI;
    using System.Web.UI.HtmlControls;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint;
    using System.Configuration;
    using System;
    using System.Text;
    using System.Web.Profile;
    using System.Web.Caching;
    using System.Collections;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.Collections.Specialized;
    using System.Web.SessionState;
    
    
    public partial class ParticipantesReuniao {
        
        protected global::System.Web.UI.WebControls.Label lblErro;
        
        protected global::DevExpress.Web.ASPxEditors.ASPxComboBox cboReunioes;
        
        protected global::Microsoft.SharePoint.WebControls.PeopleEditor pppAdd;
        
        protected global::System.Web.UI.WebControls.Button btnIncluir;
        
        protected global::System.Web.UI.WebControls.Panel pnlAdd;
        
        protected global::System.Web.UI.WebControls.ObjectDataSource dsGridMain;
        
        protected global::DevExpress.Web.ASPxGridView.ASPxGridView grid;
        
        public static implicit operator global::System.Web.UI.TemplateControl(ParticipantesReuniao target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblErro() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblErro = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblErro";
            @__ctrl.Visible = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxEditors.ASPxComboBox @__BuildControlcboReunioes() {
            global::DevExpress.Web.ASPxEditors.ASPxComboBox @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxEditors.ASPxComboBox();
            this.cboReunioes = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ApplyStyleSheetThemeInternal();
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(140, System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.ID = "cboReunioes";
            @__ctrl.TextField = "dt_evento";
            @__ctrl.ValueField = "ID";
            @__ctrl.ValueType = typeof(int);
            @__ctrl.AutoPostBack = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::Microsoft.SharePoint.WebControls.PeopleEditor @__BuildControlpppAdd() {
            global::Microsoft.SharePoint.WebControls.PeopleEditor @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.PeopleEditor();
            this.pppAdd = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "pppAdd";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100, System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.BorderStyle = System.Web.UI.WebControls.BorderStyle.Solid;
            @__ctrl.BorderColor = System.Drawing.Color.Black;
            @__ctrl.BorderWidth = new System.Web.UI.WebControls.Unit(1, System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.MultiSelect = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnIncluir() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnIncluir = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnIncluir";
            @__ctrl.Text = "Adicionar";
            @__ctrl.CssClass = "btn-small btn-primary";
            @__ctrl.Click -= new System.EventHandler(this.btnIncluir_Click);
            @__ctrl.Click += new System.EventHandler(this.btnIncluir_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Panel @__BuildControlpnlAdd() {
            global::System.Web.UI.WebControls.Panel @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Panel();
            this.pnlAdd = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "pnlAdd";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

<table style=""width:300px;"">
    <tr>

                <td style=""width:70px"">Participante:</td>
                <td>  

                    <table style=""width:100%"">
                        <tr>

                            <td>
                                "));
            global::Microsoft.SharePoint.WebControls.PeopleEditor @__ctrl1;
            @__ctrl1 = this.@__BuildControlpppAdd();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                            </td>\r\n\r\n                        </tr>\r\n         " +
                        "                   \r\n                        <tr>\r\n                            <" +
                        "td> "));
            global::System.Web.UI.WebControls.Button @__ctrl2;
            @__ctrl2 = this.@__BuildControlbtnIncluir();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(" </td>\r\n                      </tr>\r\n                    </table>\r\n\r\n            " +
                        "    </td>\r\n            </tr>\r\n</table>\r\n\r\n"));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ControlParameter @__BuildControl__control3() {
            global::System.Web.UI.WebControls.ControlParameter @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ControlParameter();
            @__ctrl.ControlID = "cboReunioes";
            @__ctrl.Name = "id_reuniao";
            @__ctrl.PropertyName = "Value";
            @__ctrl.Type = System.TypeCode.String;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control2(System.Web.UI.WebControls.ParameterCollection @__ctrl) {
            global::System.Web.UI.WebControls.ControlParameter @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control3();
            @__ctrl.Add(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.ObjectDataSource @__BuildControldsGridMain() {
            global::System.Web.UI.WebControls.ObjectDataSource @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ObjectDataSource();
            this.dsGridMain = @__ctrl;
            @__ctrl.ID = "dsGridMain";
            @__ctrl.SelectMethod = "ListaUsuarios";
            @__ctrl.TypeName = "com.sandigital.sharepoint.webparts.ParticipantesReuniao.ParticipantesReuniao";
            this.@__BuildControl__control2(@__ctrl.SelectParameters);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control4(DevExpress.Web.ASPxGridView.ASPxGridViewPagerSettings @__ctrl) {
            @__ctrl.Mode = DevExpress.Web.ASPxGridView.GridViewPagerMode.ShowAllRecords;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control5(DevExpress.Web.ASPxGridView.GridViewClientSideEvents @__ctrl) {
            @__ctrl.Init = "grid_Init";
            @__ctrl.BeginCallback = "grid_BeginCallback";
            @__ctrl.EndCallback = "grid_EndCallback";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control6(DevExpress.Web.ASPxGridView.ASPxGridViewTextSettings @__ctrl) {
            @__ctrl.EmptyDataRow = "Sem participantes ";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control10() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblUsr";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control10);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public void @__DataBinding__control10(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Label dataBindingExpressionBuilderTarget;
            DevExpress.Web.ASPxGridView.GridViewDataItemTemplateContainer Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Label)(sender));
            Container = ((DevExpress.Web.ASPxGridView.GridViewDataItemTemplateContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.Text = System.Convert.ToString(Eval ("nome") , System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control9(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control10();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataColumn @__BuildControl__control8() {
            global::DevExpress.Web.ASPxGridView.GridViewDataColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataColumn();
            @__ctrl.DataItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control9));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control13(DevExpress.Web.ASPxClasses.ImageProperties @__ctrl) {
            @__ctrl.Url = "~/Images/Excluir.png";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control12(DevExpress.Web.ASPxGridView.GridViewCommandColumnButton @__ctrl) {
            @__ctrl.Text = "Remover";
            @__ctrl.Visible = true;
            this.@__BuildControl__control13(@__ctrl.Image);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewCommandColumn @__BuildControl__control11() {
            global::DevExpress.Web.ASPxGridView.GridViewCommandColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewCommandColumn();
            @__ctrl.ButtonType = System.Web.UI.WebControls.ButtonType.Image;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(15, System.Web.UI.WebControls.UnitType.Pixel);
            this.@__BuildControl__control12(@__ctrl.DeleteButton);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control7(DevExpress.Web.ASPxGridView.GridViewColumnCollection @__ctrl) {
            global::DevExpress.Web.ASPxGridView.GridViewDataColumn @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control8();
            @__ctrl.Add(@__ctrl1);
            global::DevExpress.Web.ASPxGridView.GridViewCommandColumn @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control11();
            @__ctrl.Add(@__ctrl2);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control14(DevExpress.Web.ASPxGridView.ASPxGridViewBehaviorSettings @__ctrl) {
            @__ctrl.AllowDragDrop = false;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control15(DevExpress.Web.ASPxGridView.ASPxGridViewPagerSettings @__ctrl) {
            @__ctrl.Visible = false;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control16(DevExpress.Web.ASPxGridView.ASPxGridViewSettings @__ctrl) {
            @__ctrl.ShowColumnHeaders = false;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control17(DevExpress.Web.ASPxGridView.ASPxGridViewLoadingPanelSettings @__ctrl) {
            @__ctrl.Mode = DevExpress.Web.ASPxGridView.GridViewLoadingPanelMode.Disabled;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.ASPxGridView @__BuildControlgrid() {
            global::DevExpress.Web.ASPxGridView.ASPxGridView @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.ASPxGridView();
            this.grid = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ApplyStyleSheetThemeInternal();
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100, System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.Settings.ShowColumnHeaders = false;
            @__ctrl.ID = "grid";
            @__ctrl.ClientInstanceName = "grid";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.DataSourceID = "dsGridMain";
            @__ctrl.KeyFieldName = "id_registro";
            this.@__BuildControl__control4(@__ctrl.SettingsPager);
            this.@__BuildControl__control15(@__ctrl.SettingsPager);
            this.@__BuildControl__control5(@__ctrl.ClientSideEvents);
            this.@__BuildControl__control6(@__ctrl.SettingsText);
            this.@__BuildControl__control7(@__ctrl.Columns);
            this.@__BuildControl__control14(@__ctrl.SettingsBehavior);
            this.@__BuildControl__control16(@__ctrl.Settings);
            this.@__BuildControl__control17(@__ctrl.SettingsLoadingPanel);
            @__ctrl.RowDeleting -= new DevExpress.Web.Data.ASPxDataDeletingEventHandler(this.grid_RowDeleting);
            @__ctrl.RowDeleting += new DevExpress.Web.Data.ASPxDataDeletingEventHandler(this.grid_RowDeleting);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::com.sandigital.sharepoint.webparts.ParticipantesReuniao.ParticipantesReuniao @__ctrl) {
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllblErro();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

    
        <!-- inicio do script do Grid -->
    <script type=""text/javascript"">
        // <![CDATA[
        var timeout;
        function scheduleGridUpdate(grid) {
            window.clearTimeout(timeout);
            timeout = window.setTimeout(
                function () { /*grid.Refresh();*/ },
                5000
            );
        }
        function grid_Init(s, e) {
            scheduleGridUpdate(s);
        }
        function grid_BeginCallback(s, e) {
            window.clearTimeout(timeout);
        }
        function grid_EndCallback(s, e) {
            scheduleGridUpdate(s);
        }
        // ]]> 
    </script>
        <!-- Fim do script do Grid -->








        <table style=""width:100%;padding:5px 5px 5px 5px;"">
            <tr style=""padding-bottom:5px"">
                <td style=""width:72px;padding:5px 5px 5px 5px;"" >Reunião:</td>
                <td>"));
            global::DevExpress.Web.ASPxEditors.ASPxComboBox @__ctrl2;
            @__ctrl2 = this.@__BuildControlcboReunioes();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(" </td>\r\n            </tr>\r\n            \r\n        </table>\r\n\r\n\r\n"));
            global::System.Web.UI.WebControls.Panel @__ctrl3;
            @__ctrl3 = this.@__BuildControlpnlAdd();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n        <br />\r\n\r\n        <table style=\"width:100%\">\r\n\r\n            <tr>\r" +
                        "\n                <td>\r\n                    \r\n\r\n                    "));
            global::System.Web.UI.WebControls.ObjectDataSource @__ctrl4;
            @__ctrl4 = this.@__BuildControldsGridMain();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n                    "));
            global::DevExpress.Web.ASPxGridView.ASPxGridView @__ctrl5;
            @__ctrl5 = this.@__BuildControlgrid();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </td>\r\n            </tr>\r\n\r\n        </table>\r\n           \r\n\r\n\r\n" +
                        "\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
