//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sandigital.sharepoint.webparts.ExportadorPautas {
    using DevExpress.Web.ASPxEditors;
    using System.Web.Security;
    using DevExpress.Web.ASPxGridView;
    using System.Web.UI.WebControls;
    using System.Web;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Web.UI;
    using System.Web.UI.HtmlControls;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint;
    using System.Configuration;
    using System;
    using System.Text;
    using System.Web.Profile;
    using System.Web.Caching;
    using System.Collections;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.Collections.Specialized;
    using System.Web.SessionState;
    using DevExpress.Web.ASPxGridView.Export;
    
    
    public partial class ExportadorPautas {
        
        protected global::DevExpress.Web.ASPxGridView.ASPxGridView grdMain;
        
        protected global::DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter grdMainExport;
        
        protected global::System.Web.UI.WebControls.LinkButton lnkF;
        
        public static implicit operator global::System.Web.UI.TemplateControl(ExportadorPautas target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.ASPxGridView @__BuildControlgrdMain() {
            global::DevExpress.Web.ASPxGridView.ASPxGridView @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.ASPxGridView();
            this.grdMain = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ApplyStyleSheetThemeInternal();
            @__ctrl.ID = "grdMain";
            @__ctrl.AutoGenerateColumns = true;
            @__ctrl.Theme = "PlasticBlue";
            @__ctrl.Visible = false;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100, System.Web.UI.WebControls.UnitType.Percentage);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter @__BuildControlgrdMainExport() {
            global::DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter();
            this.grdMainExport = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdMainExport";
            @__ctrl.GridViewID = "grdMain";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControllnkF() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            this.lnkF = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lnkF";
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<div style=\"text-align:center; vertical-align:middle;width:100%;padding-left:20" +
                        "px;padding-top:10px;\">\r\n\r\n\r\n    <div style=\"text-align:left;width:28px;float:lef" +
                        "t; min-height:30px;height:30px; \">\r\n\r\n    <img \r\n        \r\n         Width=\"25\" s" +
                        "rc=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFoAAABaCAMAAAAPdrEwAAAAkFBMVE" +
                        "X///8fcUQgdkcebEEgdEYebkIeb0MebUIdbEEebUHt8u8HcDwAYyxnmHpmlHjp7uuAqZEpdUqwxbe2yb" +
                        "3X5t0AaDV/pI3Q39Y7gluet6Zrn4L2+Pbi6uW20cKev6wKbDtIhmRwm4CNtZ6Kq5epx7Zck3MyfVPC0s" +
                        "jC2MtKjGWUtKFQjmw2eFFVimp4pIkAXB3a9ih+AAAEOklEQVRYhe2ZaXOqMBSGDaIQBAU1grIcRQHrwv" +
                        "3//+4mobLUliDED53pO2VGKj4ccrYkjEZ/Gij/PVQjcFeXiyEZS6Hbo3Xf38AL5FH99Wkzv98cpOkY63" +
                        "i/kMFcBG6cINMkBFOoPh6P9bE+DO37hpstj1Zq/jMJnlBpGsZjhtb7o/0gcMP4cPUcQsgEoel0OhzN/J" +
                        "8t7cRTERACiGJRDa31QvOgiuI8SWcmAVBVVKiBrqxeGyJ9xr7vnuLc2qfKbAaKWqgV7eS2SBeXo43DTF" +
                        "EUeqiq0gU91kCsfcbRFkMr3dHYUUVCsDF6oHUvWwt0Tsx5L7Q4Qoz529CLF9FVXAvL06voymphUe2N9k" +
                        "5hKRq/bljT2RiE1hxU6jga2agmzx2Apse0JAFFb6AiwyA0ZaMmGr0PPdxq7VdaXZUnxL9XH2jCP/JjIF" +
                        "r33KAUBRhBXX5HNKLNnAok1RBax0vw9JrH0Sm74zqazkP8Sqz7+43zn9BwpazwnHM83PmV57SB1rFZ6t" +
                        "9mNDqYtXPl57EmOb+tW6C37LO/IU036j2zUTlz3JVeD86a38bDzbjGPYMPdtzsLaEuPLLxMI5TLCmuHW" +
                        "72OgUEWWW0FDTY3OwdITv2rR+Tp2z8MtaoK1r94N+GRD1x8x38tahiUsqkEbIxa+dpezZe2BD76Z23QN" +
                        "t8ysZb7y4DCQsMP+JODMjkuTcKVzM/J/qJ/dZdsYty85uO3lJDFu01BBI2FL7BRxq+mU4m1kMJ9Udk1Z" +
                        "Sv260m4ePJYmb0U1GtZo2EuZHUzgVuVEnyOZqBB7J748Nsm0jvMrAu0CGSjSb2Y8GQfDcgX8vTKwPiuA" +
                        "83rsh36GY2HurZ6LSjwWb/XvAIvMJzXN8u21K0gmXbmpZBK5o/lB/xurcypc5UudGGF/HR9kBeoispL9" +
                        "ghsfizhc/lyTlUWtKuUTs92G0DAhtu7fWzqBoWeSqqVUDwokpqEdKajYXRZ4WGIB/TlTORlI1QtPSclB" +
                        "ZYICllCt6azZ9M3hNGS0cwU+2InhWdMQZ+HfdJMAcpA1Jkk+EVF3JHjiLUmo2de6OV2/ZlV9hALI6mla" +
                        "QZfNauFL35aVeT3d4KavNJx7taeZxozemkjHUjmqAJJk+T4Petdm9xVIomwTmq6bQYgh7rwLam+F/RG8" +
                        "njVNwbX1yBvXFJ+jvRHbOxy/Jf/5KNpGM2dgm+PH7IphOWlR1Xitp7owgtfxfnhT3V/la/Ef3GHTPhZK" +
                        "H3FqK3XQq03ZOe5ckUCiAulrNeysigdN1kdoRKD4U/DPe8vOTJB98cF6PxbbkSKauFPtvSD6M4v/ItfU" +
                        "Fc93mb5BvrzxcRU1ruoXfw/Rw6QeCe4t3dQ6x9aDJenjQfwGcuOCYp8zeWin7cwQiyyxUYHutsc2jwi6" +
                        "onnaPNfO85U2o7SEYzLZiLrfvtLh/NxN7lZe95T/qnAfoPKAbT+JDDCk4AAAAASUVORK5CYII=\"\r\n   " +
                        "     />\r\n\r\n   </div>\r\n\r\n    <div style=\"float:left;vertical-align:middle;min-hei" +
                        "ght:30px; height:30px;padding-top:5px;padding-left:10px\">\r\nExportar pautas para " +
                        "Excel.\r\n</div>\r\n\r\n</div>\r\n\r\n"));
            @__ctrl.Click -= new System.EventHandler(this.lnkF_Click);
            @__ctrl.Click += new System.EventHandler(this.lnkF_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::com.sandigital.sharepoint.webparts.ExportadorPautas.ExportadorPautas @__ctrl) {
            global::DevExpress.Web.ASPxGridView.ASPxGridView @__ctrl1;
            @__ctrl1 = this.@__BuildControlgrdMain();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            global::DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter @__ctrl2;
            @__ctrl2 = this.@__BuildControlgrdMainExport();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n "));
            global::System.Web.UI.WebControls.LinkButton @__ctrl3;
            @__ctrl3 = this.@__BuildControllnkF();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n<br /><br />\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
