//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sandigital.sharepoint.webparts.GirGrd {
    using DevExpress.Web.ASPxEditors;
    using System.Web.Security;
    using DevExpress.Web.ASPxGridView;
    using System.Web.UI.WebControls;
    using System.Web;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Web.UI;
    using System.Web.UI.HtmlControls;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint;
    using System.Configuration;
    using System;
    using System.Text;
    using System.Web.Profile;
    using System.Web.Caching;
    using System.Collections;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.Collections.Specialized;
    using System.Web.SessionState;
    
    
    public partial class GirGrd {
        
        protected global::DevExpress.Web.ASPxGridView.ASPxGridView grdMain;
        
        protected global::System.Web.UI.WebControls.Label lblErro;
        
        public static implicit operator global::System.Web.UI.TemplateControl(GirGrd target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control3(DevExpress.Web.ASPxGridView.GridViewHeaderStyle @__ctrl) {
            @__ctrl.BackColor = System.Drawing.Color.White;
            @__ctrl.CssClass = "boxAuxiliarPeq";
            @__ctrl.Font.Bold = true;
            @__ctrl.ForeColor = ((System.Drawing.Color)(System.Drawing.Color.FromArgb(0, 61, 117)));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control5(DevExpress.Web.ASPxClasses.Border @__ctrl) {
            @__ctrl.BorderColor = ((System.Drawing.Color)(System.Drawing.Color.FromArgb(206, 220, 229)));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control4(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            this.@__BuildControl__control5(@__ctrl.BorderBottom);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control6(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.CssClass = "boxGirGrdPager";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control2(DevExpress.Web.ASPxGridView.GridViewStyles @__ctrl) {
            this.@__BuildControl__control3(@__ctrl.Header);
            this.@__BuildControl__control4(@__ctrl.Cell);
            this.@__BuildControl__control6(@__ctrl.PagerBottomPanel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control8(DevExpress.Web.ASPxPager.AllButtonProperties @__ctrl) {
            @__ctrl.Text = "All";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control9(DevExpress.Web.ASPxPager.SummaryProperties @__ctrl) {
            @__ctrl.AllPagesText = "Páginas: {0} - {1} ({2} itens)";
            @__ctrl.Text = "Página  {0} de {1} ({2} itens)";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control7(DevExpress.Web.ASPxGridView.ASPxGridViewPagerSettings @__ctrl) {
            @__ctrl.PageSize = 5;
            @__ctrl.EllipsisMode = DevExpress.Web.ASPxPager.PagerEllipsisMode.OutsideNumeric;
            this.@__BuildControl__control8(@__ctrl.AllButton);
            this.@__BuildControl__control9(@__ctrl.Summary);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control10(DevExpress.Web.ASPxClasses.BorderWrapper @__ctrl) {
            @__ctrl.BorderStyle = System.Web.UI.WebControls.BorderStyle.None;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control15() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblTextoSGIR";
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control15);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public void @__DataBinding__control15(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Label dataBindingExpressionBuilderTarget;
            DevExpress.Web.ASPxGridView.GridViewDataItemTemplateContainer Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Label)(sender));
            Container = ((DevExpress.Web.ASPxGridView.GridViewDataItemTemplateContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.Text = System.Convert.ToString( Eval("SGIR") , System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__control14() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lnkSGIR";
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control15();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control14);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public void @__DataBinding__control14(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.HyperLink dataBindingExpressionBuilderTarget;
            DevExpress.Web.ASPxGridView.GridViewDataItemTemplateContainer Container;
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.HyperLink)(sender));
            Container = ((DevExpress.Web.ASPxGridView.GridViewDataItemTemplateContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            dataBindingExpressionBuilderTarget.NavigateUrl = System.Convert.ToString( string.Format("http://ENDERECO_S_GIR?SGIR={0}", Eval("SGIR")) , System.Globalization.CultureInfo.CurrentCulture);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control13(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    \r\n                    "));
            global::System.Web.UI.WebControls.HyperLink @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control14();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control16(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Left;
            @__ctrl.ForeColor = ((System.Drawing.Color)(System.Drawing.Color.FromArgb(0, 61, 117)));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control17(DevExpress.Web.ASPxGridView.GridViewHeaderStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Left;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control12() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.DataItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control13));
            @__ctrl.FieldName = "SGIR";
            @__ctrl.Caption = "SGIR";
            @__ctrl.VisibleIndex = 0;
            this.@__BuildControl__control16(@__ctrl.CellStyle);
            this.@__BuildControl__control17(@__ctrl.HeaderStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control18() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.FieldName = "Grd";
            @__ctrl.Caption = "GRD";
            @__ctrl.VisibleIndex = 1;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control20(DevExpress.Web.ASPxEditors.DateEditProperties @__ctrl) {
            @__ctrl.DisplayFormatString = "dd/MMM HH:mm";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control21(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Left;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control22(DevExpress.Web.ASPxGridView.GridViewHeaderStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Left;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataDateColumn @__BuildControl__control19() {
            global::DevExpress.Web.ASPxGridView.GridViewDataDateColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataDateColumn();
            @__ctrl.Caption = "INÍCIO";
            @__ctrl.FieldName = "Inicio";
            @__ctrl.VisibleIndex = 2;
            this.@__BuildControl__control20(@__ctrl.PropertiesDateEdit);
            this.@__BuildControl__control21(@__ctrl.CellStyle);
            this.@__BuildControl__control22(@__ctrl.HeaderStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control24(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Left;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control25(DevExpress.Web.ASPxGridView.GridViewHeaderStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Left;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control23() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.FieldName = "Rede";
            @__ctrl.Caption = "REDE";
            @__ctrl.VisibleIndex = 3;
            this.@__BuildControl__control24(@__ctrl.CellStyle);
            this.@__BuildControl__control25(@__ctrl.HeaderStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control26() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.FieldName = "Atividade";
            @__ctrl.Caption = "ATIVIDADE";
            @__ctrl.VisibleIndex = 4;
            @__ctrl.Visible = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control28(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Left;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control29(DevExpress.Web.ASPxGridView.GridViewHeaderStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Left;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control27() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.FieldName = "Localidade";
            @__ctrl.Caption = "LOCALIDADES";
            @__ctrl.VisibleIndex = 5;
            this.@__BuildControl__control28(@__ctrl.CellStyle);
            this.@__BuildControl__control29(@__ctrl.HeaderStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control11(DevExpress.Web.ASPxGridView.GridViewColumnCollection @__ctrl) {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control12();
            @__ctrl.Add(@__ctrl1);
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control18();
            @__ctrl.Add(@__ctrl2);
            global::DevExpress.Web.ASPxGridView.GridViewDataDateColumn @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control19();
            @__ctrl.Add(@__ctrl3);
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control23();
            @__ctrl.Add(@__ctrl4);
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl5;
            @__ctrl5 = this.@__BuildControl__control26();
            @__ctrl.Add(@__ctrl5);
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl6;
            @__ctrl6 = this.@__BuildControl__control27();
            @__ctrl.Add(@__ctrl6);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control30(DevExpress.Web.ASPxGridView.ASPxGridViewSettings @__ctrl) {
            @__ctrl.GridLines = System.Web.UI.WebControls.GridLines.Horizontal;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.ASPxGridView @__BuildControlgrdMain() {
            global::DevExpress.Web.ASPxGridView.ASPxGridView @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.ASPxGridView();
            this.grdMain = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ApplyStyleSheetThemeInternal();
            @__ctrl.ID = "grdMain";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100, System.Web.UI.WebControls.UnitType.Percentage);
            this.@__BuildControl__control2(@__ctrl.Styles);
            this.@__BuildControl__control7(@__ctrl.SettingsPager);
            this.@__BuildControl__control10(@__ctrl.Border);
            this.@__BuildControl__control11(@__ctrl.Columns);
            this.@__BuildControl__control30(@__ctrl.Settings);
            @__ctrl.PageIndexChanged -= new System.EventHandler(this.grdMain_PageIndexChanged);
            @__ctrl.PageIndexChanged += new System.EventHandler(this.grdMain_PageIndexChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblErro() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblErro = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblErro";
            @__ctrl.Visible = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::com.sandigital.sharepoint.webparts.GirGrd.GirGrd @__ctrl) {
            global::DevExpress.Web.ASPxGridView.ASPxGridView @__ctrl1;
            @__ctrl1 = this.@__BuildControlgrdMain();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        \r\n \r\n\r\n\r\n                   \r\n"));
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControllblErro();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
