//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sandigital.sharepoint.webparts.VisualizadorDeListaAgrupada {
    using DevExpress.Web.ASPxEditors;
    using System.Web.Security;
    using DevExpress.Web.ASPxGridView;
    using System.Web.UI.WebControls;
    using System.Web;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Web.UI;
    using System.Web.UI.HtmlControls;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint;
    using System.Configuration;
    using System;
    using System.Text;
    using System.Web.Profile;
    using System.Web.Caching;
    using System.Collections;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.Collections.Specialized;
    using System.Web.SessionState;
    
    
    public partial class VisualizadorDeListaAgrupada {
        
        protected global::System.Web.UI.WebControls.Label lblHack;
        
        protected global::System.Web.UI.WebControls.Label lblErro;
        
        protected global::DevExpress.Web.ASPxGridView.ASPxGridView dGridMain;
        
        public static implicit operator global::System.Web.UI.TemplateControl(VisualizadorDeListaAgrupada target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblHack() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblHack = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblHack";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblErro() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblErro = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblErro";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control2(DevExpress.Web.ASPxGridView.ASPxGridViewBehaviorSettings @__ctrl) {
            @__ctrl.SortMode = DevExpress.XtraGrid.ColumnSortMode.Custom;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control3(DevExpress.Web.ASPxGridView.ASPxGridViewPagerSettings @__ctrl) {
            @__ctrl.Mode = DevExpress.Web.ASPxGridView.GridViewPagerMode.ShowAllRecords;
            @__ctrl.Visible = false;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control4(DevExpress.Web.ASPxGridView.ASPxGridViewSettings @__ctrl) {
            @__ctrl.GridLines = System.Web.UI.WebControls.GridLines.None;
            @__ctrl.GroupFormat = "{0}:  <span class=\'ms-gb2\' style=\'border:none;color:#4c4c4c\'>  {1} {2} </spam>";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control5(DevExpress.Web.ASPxGridView.ASPxGridViewLoadingPanelSettings @__ctrl) {
            @__ctrl.Text = "Carregando&hellip;";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control7(DevExpress.Web.ASPxClasses.ImageProperties @__ctrl) {
            @__ctrl.Url = "/_layouts/images/plus.gif";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control8(DevExpress.Web.ASPxClasses.ImageProperties @__ctrl) {
            @__ctrl.Url = "/_layouts/images/minus.gif";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control6(DevExpress.Web.ASPxGridView.GridViewImages @__ctrl) {
            this.@__BuildControl__control7(@__ctrl.CollapsedButton);
            this.@__BuildControl__control8(@__ctrl.ExpandedButton);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control11(DevExpress.Web.ASPxClasses.Paddings @__ctrl) {
            @__ctrl.PaddingBottom = new System.Web.UI.WebControls.Unit(5, System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.PaddingTop = new System.Web.UI.WebControls.Unit(5, System.Web.UI.WebControls.UnitType.Pixel);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control12(DevExpress.Web.ASPxClasses.BorderWrapper @__ctrl) {
            @__ctrl.BorderStyle = System.Web.UI.WebControls.BorderStyle.None;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control10(DevExpress.Web.ASPxGridView.GridViewHeaderStyle @__ctrl) {
            @__ctrl.BackColor = System.Drawing.Color.Transparent;
            this.@__BuildControl__control11(@__ctrl.Paddings);
            this.@__BuildControl__control12(@__ctrl.Border);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control13(DevExpress.Web.ASPxGridView.GridViewGroupRowStyle @__ctrl) {
            @__ctrl.BackColor = System.Drawing.Color.Transparent;
            @__ctrl.CssClass = "ms-gb";
            @__ctrl.Font.Bold = true;
            @__ctrl.ForeColor = ((System.Drawing.Color)(System.Drawing.Color.FromArgb(0, 114, 188)));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control14(DevExpress.Web.ASPxGridView.GridViewDataRowStyle @__ctrl) {
            @__ctrl.CssClass = "ms-vb2 ms-itmhover";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control16(DevExpress.Web.ASPxClasses.BorderWrapper @__ctrl) {
            @__ctrl.BorderStyle = System.Web.UI.WebControls.BorderStyle.None;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control15(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            this.@__BuildControl__control16(@__ctrl.Border);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control18(DevExpress.Web.ASPxClasses.BorderWrapper @__ctrl) {
            @__ctrl.BorderStyle = System.Web.UI.WebControls.BorderStyle.None;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control17(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.BackColor = System.Drawing.Color.Transparent;
            this.@__BuildControl__control18(@__ctrl.Border);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control20(DevExpress.Web.ASPxClasses.BorderWrapper @__ctrl) {
            @__ctrl.BorderStyle = System.Web.UI.WebControls.BorderStyle.None;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control19(DevExpress.Web.ASPxGridView.GridViewGroupFooterStyle @__ctrl) {
            this.@__BuildControl__control20(@__ctrl.Border);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control22(DevExpress.Web.ASPxClasses.BorderWrapper @__ctrl) {
            @__ctrl.BorderStyle = System.Web.UI.WebControls.BorderStyle.None;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control21(DevExpress.Web.ASPxGridView.GridViewGroupPanelStyle @__ctrl) {
            this.@__BuildControl__control22(@__ctrl.Border);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control24(DevExpress.Web.ASPxClasses.BorderWrapper @__ctrl) {
            @__ctrl.BorderStyle = System.Web.UI.WebControls.BorderStyle.None;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control23(DevExpress.Web.ASPxGridView.GridViewHeaderPanelStyle @__ctrl) {
            this.@__BuildControl__control24(@__ctrl.Border);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control26(DevExpress.Web.ASPxClasses.BorderWrapper @__ctrl) {
            @__ctrl.BorderStyle = System.Web.UI.WebControls.BorderStyle.None;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control25(DevExpress.Web.ASPxGridView.GridViewStatusBarStyle @__ctrl) {
            this.@__BuildControl__control26(@__ctrl.Border);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control28(DevExpress.Web.ASPxClasses.BorderWrapper @__ctrl) {
            @__ctrl.BorderStyle = System.Web.UI.WebControls.BorderStyle.None;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control27(DevExpress.Web.ASPxEditors.ListBoxItemStyle @__ctrl) {
            this.@__BuildControl__control28(@__ctrl.Border);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control9(DevExpress.Web.ASPxGridView.GridViewStyles @__ctrl) {
            this.@__BuildControl__control10(@__ctrl.Header);
            this.@__BuildControl__control13(@__ctrl.GroupRow);
            this.@__BuildControl__control14(@__ctrl.Row);
            this.@__BuildControl__control15(@__ctrl.DetailCell);
            this.@__BuildControl__control17(@__ctrl.Cell);
            this.@__BuildControl__control19(@__ctrl.GroupFooter);
            this.@__BuildControl__control21(@__ctrl.GroupPanel);
            this.@__BuildControl__control23(@__ctrl.HeaderPanel);
            this.@__BuildControl__control25(@__ctrl.StatusBar);
            this.@__BuildControl__control27(@__ctrl.HeaderFilterItem);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control29(DevExpress.Web.ASPxClasses.BorderWrapper @__ctrl) {
            @__ctrl.BorderStyle = System.Web.UI.WebControls.BorderStyle.None;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.ASPxGridView @__BuildControldGridMain() {
            global::DevExpress.Web.ASPxGridView.ASPxGridView @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.ASPxGridView();
            this.dGridMain = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ApplyStyleSheetThemeInternal();
            @__ctrl.Visible = false;
            @__ctrl.ID = "dGridMain";
            @__ctrl.AutoGenerateColumns = true;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100, System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.EnableTheming = true;
            this.@__BuildControl__control2(@__ctrl.SettingsBehavior);
            this.@__BuildControl__control3(@__ctrl.SettingsPager);
            this.@__BuildControl__control4(@__ctrl.Settings);
            this.@__BuildControl__control5(@__ctrl.SettingsLoadingPanel);
            this.@__BuildControl__control6(@__ctrl.Images);
            this.@__BuildControl__control9(@__ctrl.Styles);
            this.@__BuildControl__control29(@__ctrl.Border);
            @__ctrl.CustomColumnSort -= new DevExpress.Web.ASPxGridView.ASPxGridViewCustomColumnSortEventHandler(this.dGridMain_CustomColumnSort);
            @__ctrl.CustomColumnSort += new DevExpress.Web.ASPxGridView.ASPxGridViewCustomColumnSortEventHandler(this.dGridMain_CustomColumnSort);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::com.sandigital.sharepoint.webparts.VisualizadorDeListaAgrupada.VisualizadorDeListaAgrupada @__ctrl) {
            global::System.Web.UI.WebControls.Label @__ctrl1;
            @__ctrl1 = this.@__BuildControllblHack();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControllblErro();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

   <style type=""text/css"">
            .dxgvIndentCell {
                background-color:transparent !important;
                            border: 0px !important;

            }

             .dxgvGroupRow td , dxgvGroupRow {
            border: 0px !important;
        }

        </style>

"));
            global::DevExpress.Web.ASPxGridView.ASPxGridView @__ctrl3;
            @__ctrl3 = this.@__BuildControldGridMain();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"

	<script type=""text/javascript"" src=""/js/jquery.min.js""></script>


<script type=""text/javascript"">

    $(document).ready(function () {

        var hack = $("".ag_hackTitulo"");

        $(hack).each(function () {
            $($(this).closest(""tbody"")).find("".ms-WPHeaderTd h3 nobr"").html(""<a href='"" + $(this).attr(""url"")  + ""'>""+ $(this).attr(""titulo"") +""</a>"")
        });
        //

    });
    

</script>










"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
