//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sandigital.sharepoint.webparts.MeusSistemas {
    using System.Web;
    using System.Text.RegularExpressions;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint.WebControls;
    using System.Web.Security;
    using Microsoft.SharePoint.Utilities;
    using System.Web.UI;
    using System;
    using System.Web.UI.WebControls;
    using System.Collections.Specialized;
    using Microsoft.SharePoint;
    using System.Collections;
    using System.Web.Profile;
    using System.Text;
    using System.Web.Caching;
    using System.Configuration;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.SessionState;
    using System.Web.UI.HtmlControls;
    
    
    public partial class MeusSistemas {
        
        public static implicit operator global::System.Web.UI.TemplateControl(MeusSistemas target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::com.sandigital.sharepoint.webparts.MeusSistemas.MeusSistemas @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n                  \r\n\r\n    <h2 class=\"meusSistemasTitulo\"><a href=" +
                        "\"#\" onclick=\"return false\" class=\"textAlt\"\r\n         title=\"Selecione e organize" +
                        " os sistemas que  você mais usa no dia a dia.\">Meus Sistemas</a></h2>\r\n\r\n\r\n\r\n \r\n" +
                        "                        \r\n                        \r\n                        \r\n  " +
                        "                        \r\n                    <ul class=\"meusSistemas\">\r\n       " +
                        "         \r\n                    <li><p class=\"itens\"><strong><a title=\"Sistema\" h" +
                        "ref=\"http://10.13.211.10/\">GCPE</a></strong></p></li>\r\n                \r\n       " +
                        "             <li><p class=\"itens\"><strong><a title=\"Sistema\" href=\"http://itp.nt" +
                        ".embratel.com.br/\">ITP</a></strong></p></li>\r\n                \r\n                " +
                        "    <li><p class=\"itens\"><strong><a title=\"Sistema\" href=\"http://ntspo902/portal" +
                        "vendas/UmSoClick/pgv/pgv.html\">PGV</a></strong></p></li>\r\n                \r\n    " +
                        "                <li><p class=\"itens\"><strong><a title=\"Sistema\" href=\"http://nth" +
                        "or053/safweb/home.aspx\">SafWeb</a></strong></p></li>\r\n                \r\n        " +
                        "            <li><p class=\"itens\"><strong><a title=\"Sistema\" href=\"http://webip.e" +
                        "mbratel.net.br/saip/menu.asp\">SAIP</a></strong></p></li>\r\n                \r\n    " +
                        "                <li><p class=\"itens\"><strong><a title=\"Sistema\" href=\"http://nts" +
                        "po902/portalvendas/UmSoClick/sistemas/pages/sistema.asp?sistema=46\">SGA</a></str" +
                        "ong></p></li>\r\n                \r\n                    <li><p class=\"itens\"><stron" +
                        "g><a title=\"Sistema\" href=\"http://10.13.54.150:20020/\">SIR</a></strong></p></li>" +
                        "\r\n                \r\n                    <li><p class=\"itens\"><strong><a title=\"S" +
                        "istema\" href=\"http://ntspo912/ssa/\">SSA</a></strong></p></li>\r\n                \r" +
                        "\n                    <li><p class=\"itens\"><strong><a title=\"Sistema\" href=\"http:" +
                        "//ntspo922/star21/logon/logon.asp\">Star 21</a></strong></p></li>\r\n              " +
                        "  \r\n                    <li><p class=\"itens\"><strong><a title=\"Sistema\" href=\"ht" +
                        "tp://ntspo912/portalda/gerenciadoprotocolo/index.asp\">GPE - Gerência do Protocol" +
                        "o da Embratel</a></strong></p></li>\r\n                \r\n                    <li><" +
                        "p class=\"itens\"><strong><a title=\"Sistema\" href=\"http://ntspo901/PORTALVPR/Proje" +
                        "tosEAdmRede/EstrategiaPortifTec/SISLAB1/index.asp\">SISLAB</a></strong></p></li>\r" +
                        "\n                \r\n                     \r\n                    </ul>\r\n           " +
                        "     \r\n <div class=\"meusSistemasDown\">\r\n <p><a href=\"/meussistemas.aspx\"  title=" +
                        "\"Meus Sistemas\" class=\"more\">Meus Sistemas</a> </p>\r\n <p><a href=\"/sistemasA-Z.a" +
                        "spx\"  title=\"Sistemas de A a Z\" class=\"more\">Sistemas de A a Z</a></p>\r\n</div>  " +
                        "    \r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
