//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sandigital.sharepoint.webparts.PainelUsuario {
    using DevExpress.Web.ASPxEditors;
    using System.Web.Security;
    using DevExpress.Web.ASPxGridView;
    using System.Web.UI.WebControls;
    using System.Web;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using DevExpress.Web.ASPxTimer;
    using System.Web.UI;
    using System.Web.UI.HtmlControls;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint;
    using System.Configuration;
    using System;
    using System.Text;
    using System.Web.Profile;
    using System.Web.Caching;
    using System.Collections;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.Collections.Specialized;
    using System.Web.SessionState;
    
    
    public partial class PainelUsuario {
        
        protected global::System.Web.UI.Timer tAtualizaGrid;
        
        protected global::DevExpress.Web.ASPxGridView.ASPxGridView dGridMain;
        
        protected global::System.Web.UI.UpdatePanel UpdatePanel2;
        
        public static implicit operator global::System.Web.UI.TemplateControl(PainelUsuario target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.Timer @__BuildControltAtualizaGrid() {
            global::System.Web.UI.Timer @__ctrl;
            @__ctrl = new global::System.Web.UI.Timer();
            this.tAtualizaGrid = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ID = "tAtualizaGrid";
            @__ctrl.Interval = 5000;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                                        "));
            @__ctrl.Tick -= new System.EventHandler<System.EventArgs>(this.tAtualizaGrid_Tick);
            @__ctrl.Tick += new System.EventHandler<System.EventArgs>(this.tAtualizaGrid_Tick);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control4() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.Caption = "Noc";
            @__ctrl.FieldName = "Noc";
            @__ctrl.VisibleIndex = 0;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control6(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Center;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control5() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.Caption = "Operador";
            @__ctrl.FieldName = "Operador";
            @__ctrl.VisibleIndex = 1;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(80, System.Web.UI.WebControls.UnitType.Pixel);
            this.@__BuildControl__control6(@__ctrl.CellStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control8(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Center;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control7() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.Caption = "Data do Inicio";
            @__ctrl.FieldName = "dt_inicio";
            @__ctrl.VisibleIndex = 2;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(80, System.Web.UI.WebControls.UnitType.Pixel);
            this.@__BuildControl__control8(@__ctrl.CellStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control10(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Center;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control9() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.Caption = "Data do Fim";
            @__ctrl.FieldName = "dt_fim";
            @__ctrl.VisibleIndex = 3;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(80, System.Web.UI.WebControls.UnitType.Pixel);
            this.@__BuildControl__control10(@__ctrl.CellStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control12(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Center;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control11() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.Caption = "Mensagens";
            @__ctrl.FieldName = "Mensagens";
            @__ctrl.VisibleIndex = 4;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(80, System.Web.UI.WebControls.UnitType.Pixel);
            this.@__BuildControl__control12(@__ctrl.CellStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control14(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Center;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control13() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.Caption = "Status";
            @__ctrl.FieldName = "Status";
            @__ctrl.VisibleIndex = 5;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(80, System.Web.UI.WebControls.UnitType.Pixel);
            this.@__BuildControl__control14(@__ctrl.CellStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.DataBoundLiteralControl @__BuildControl__control17() {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.DataBoundLiteralControl(2, 1);
            @__ctrl.TemplateControl = this;
            @__ctrl.SetStaticString(0, @"
                                                                       <a href=""javascript:void(0);"" 
                                                                            
                                                                            
                                                                           onclick='ShowWindow(&#039;/EbtChat/PopupUsuario.aspx&#039;,&#039;");
            @__ctrl.SetStaticString(1, "&#039;)\'>Exibir</a>\r\n                                                            " +
                    "       ");
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBind__control17);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public void @__DataBind__control17(object sender, System.EventArgs e) {
            DevExpress.Web.ASPxGridView.GridViewDataItemTemplateContainer Container;
            System.Web.UI.DataBoundLiteralControl target;
            target = ((System.Web.UI.DataBoundLiteralControl)(sender));
            Container = ((DevExpress.Web.ASPxGridView.GridViewDataItemTemplateContainer)(target.BindingContainer));
            target.SetDataBoundString(0, System.Convert.ToString(Container.KeyValue, System.Globalization.CultureInfo.CurrentCulture));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control16(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.DataBoundLiteralControl @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control17();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control18(DevExpress.Web.ASPxGridView.GridViewCellStyle @__ctrl) {
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Center;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__BuildControl__control15() {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn();
            @__ctrl.DataItemTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control16));
            @__ctrl.Caption = "Ações";
            @__ctrl.VisibleIndex = 6;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(60, System.Web.UI.WebControls.UnitType.Pixel);
            this.@__BuildControl__control18(@__ctrl.CellStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control3(DevExpress.Web.ASPxGridView.GridViewColumnCollection @__ctrl) {
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control4();
            @__ctrl.Add(@__ctrl1);
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control5();
            @__ctrl.Add(@__ctrl2);
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control7();
            @__ctrl.Add(@__ctrl3);
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl4;
            @__ctrl4 = this.@__BuildControl__control9();
            @__ctrl.Add(@__ctrl4);
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl5;
            @__ctrl5 = this.@__BuildControl__control11();
            @__ctrl.Add(@__ctrl5);
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl6;
            @__ctrl6 = this.@__BuildControl__control13();
            @__ctrl.Add(@__ctrl6);
            global::DevExpress.Web.ASPxGridView.GridViewDataTextColumn @__ctrl7;
            @__ctrl7 = this.@__BuildControl__control15();
            @__ctrl.Add(@__ctrl7);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control20(DevExpress.Web.ASPxPager.AllButtonProperties @__ctrl) {
            @__ctrl.Text = "All";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control21(DevExpress.Web.ASPxPager.NextButtonProperties @__ctrl) {
            @__ctrl.Text = "Next >";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control22(DevExpress.Web.ASPxPager.PrevButtonProperties @__ctrl) {
            @__ctrl.Text = "< Prev";
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control19(DevExpress.Web.ASPxGridView.ASPxGridViewPagerSettings @__ctrl) {
            @__ctrl.ShowDefaultImages = false;
            this.@__BuildControl__control20(@__ctrl.AllButton);
            this.@__BuildControl__control21(@__ctrl.NextPageButton);
            this.@__BuildControl__control22(@__ctrl.PrevPageButton);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxGridView.ASPxGridView @__BuildControldGridMain() {
            global::DevExpress.Web.ASPxGridView.ASPxGridView @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxGridView.ASPxGridView();
            this.dGridMain = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ApplyStyleSheetThemeInternal();
            @__ctrl.ID = "dGridMain";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.KeyFieldName = "id_atendimento";
            this.@__BuildControl__control3(@__ctrl.Columns);
            this.@__BuildControl__control19(@__ctrl.SettingsPager);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control2(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                                      "));
            global::System.Web.UI.Timer @__ctrl1;
            @__ctrl1 = this.@__BuildControltAtualizaGrid();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("     \r\n\r\n\r\n                                                       "));
            global::DevExpress.Web.ASPxGridView.ASPxGridView @__ctrl2;
            @__ctrl2 = this.@__BuildControldGridMain();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                                   "));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.UpdatePanel @__BuildControlUpdatePanel2() {
            global::System.Web.UI.UpdatePanel @__ctrl;
            @__ctrl = new global::System.Web.UI.UpdatePanel();
            this.UpdatePanel2 = @__ctrl;
            @__ctrl.ContentTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control2));
            @__ctrl.ID = "UpdatePanel2";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::com.sandigital.sharepoint.webparts.PainelUsuario.PainelUsuario @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"








<script  type=""text/javascript"" >

    function ShowWindow(url, keyValue) {

        window.open(url + '?id_atendimento=' + keyValue, ""janela"" + keyValue, ""width=650,height=350,scrollbars=NO"")

    }

  

</script>




<div style=""background-color:#dedfde;color:#ffffff;"">
<table width=""100%"" cellpadding=""0"" cellspacing=""0""  >
    <tr valign=""top"">
        <td align=""left"">     
            <table width=""100%"" cellpadding=""0"" cellspacing=""0""  >                                      
                                                                                              
                <tr valign=""top"">
                    <td>                                                                                 
                        <table width=""100%"" cellpadding=""0"" cellspacing=""0"" id=""outros_chats""  >            
                            <tr>
                                <td style=""padding-top:20px;padding-bottom:20px;padding-left:10px;"">
                                    <table cellpadding=""0"" cellspacing=""0"">
                                        <tr>
                                           <td >       
                                               "));
            global::System.Web.UI.UpdatePanel @__ctrl1;
            @__ctrl1 = this.@__BuildControlUpdatePanel2();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"                                                                                                                                                                                                   
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align=""right"" style=""padding-top:20px"" >

                                                <a href=""InicioChat.aspx""  class=""btn btn-primary"" style=""color:white!improtant;""  >                                     
                                                      
                                                    Novo Chat

                                                </a>    
                                            </td>
                                        </tr>
                                    </table> 
                                                             
                                </td>
                            </tr>
                        </table>                                                                       
                    </td>
                </tr>
            </table>
         </td>
    </tr> 
</table>
</div>
"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
