//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5483
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sandigital.sharepoint.webparts.ChatNoc {
    using System.Web;
    using System.Text.RegularExpressions;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.Security;
    using System.Text;
    using System.Web.SessionState;
    using DevExpress.Web.ASPxEditors;
    using System.Collections.Specialized;
    using Microsoft.SharePoint.WebControls;
    using System.Web.UI.WebControls;
    using System;
    using Microsoft.SharePoint;
    using System.Web.UI;
    using System.Web.Profile;
    using System.Collections;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.Caching;
    using Microsoft.SharePoint.Utilities;
    using System.Configuration;
    using System.Web.UI.HtmlControls;
    
    
    public partial class ChatNoc {
        
        protected global::System.Web.UI.WebControls.DropDownList ddlNoc;
        
        protected global::DevExpress.Web.ASPxEditors.ASPxButton btnSelecionar;
        
        public static implicit operator global::System.Web.UI.TemplateControl(ChatNoc target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlNoc() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.ddlNoc = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "ddlNoc";
            @__ctrl.CssClass = "chatDD";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxEditors.ASPxButton @__BuildControlbtnSelecionar() {
            global::DevExpress.Web.ASPxEditors.ASPxButton @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxEditors.ASPxButton();
            this.btnSelecionar = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ApplyStyleSheetThemeInternal();
            @__ctrl.Text = "Selecionar";
            @__ctrl.CssClass = "btn btn-primary";
            @__ctrl.EnableDefaultAppearance = false;
            @__ctrl.ID = "btnSelecionar";
            @__ctrl.Click -= new System.EventHandler(this.btnSelecionar_Click);
            @__ctrl.Click += new System.EventHandler(this.btnSelecionar_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::com.sandigital.sharepoint.webparts.ChatNoc.ChatNoc @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"








<script language=""javascript"" type=""text/javascript"" >

    function Redireciona(keyValue) {
        location.href = keyValue;

    }


    function ShowWindow(url, keyValue) {


        var janela = window.open(url + '?id_atendimento=' + keyValue, ""janela"" + keyValue, ""width=650,height=350,scrollbars=NO,titlebar=NO"")


        if (janela == null) {
            alert('Erro ao abrir o popup, desabilite o bloqueador de popups e tente novamente.');
            janela.close();
            return false;
        } else {
            return true;
        }




    }

</script>


<div class=""chatContainer"">

    <div class=""chatContainerDD"">
            "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl1;
            @__ctrl1 = this.@__BuildControlddlNoc();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(" \r\n    </div>\r\n   \r\n    <div class=\"chatContainerBtn\">\r\n            "));
            global::DevExpress.Web.ASPxEditors.ASPxButton @__ctrl2;
            @__ctrl2 = this.@__BuildControlbtnSelecionar();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    </div> \r\n </div>\r\n\r\n"));
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
