//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sandigital.sharepoint.webparts.ParticipantesReuniaoLista {
    using DevExpress.Web.ASPxEditors;
    using System.Web.Security;
    using DevExpress.Web.ASPxGridView;
    using System.Web.UI.WebControls;
    using System.Web;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Web.UI;
    using System.Web.UI.HtmlControls;
    using Microsoft.SharePoint.WebPartPages;
    using Microsoft.SharePoint;
    using System.Configuration;
    using System;
    using System.Text;
    using System.Web.Profile;
    using System.Web.Caching;
    using System.Collections;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.Collections.Specialized;
    using System.Web.SessionState;
    
    
    public partial class ParticipantesReuniaoLista {
        
        protected global::DevExpress.Web.ASPxEditors.ASPxComboBox cboReunioes;
        
        protected global::System.Web.UI.WebControls.Label lblErro;
        
        protected global::System.Web.UI.WebControls.GridView grdMain;
        
        public static implicit operator global::System.Web.UI.TemplateControl(ParticipantesReuniaoLista target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::DevExpress.Web.ASPxEditors.ASPxComboBox @__BuildControlcboReunioes() {
            global::DevExpress.Web.ASPxEditors.ASPxComboBox @__ctrl;
            @__ctrl = new global::DevExpress.Web.ASPxEditors.ASPxComboBox();
            this.cboReunioes = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ApplyStyleSheetThemeInternal();
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(140, System.Web.UI.WebControls.UnitType.Pixel);
            @__ctrl.ID = "cboReunioes";
            @__ctrl.TextField = "dt_evento";
            @__ctrl.ValueField = "ID";
            @__ctrl.ValueType = typeof(int);
            @__ctrl.AutoPostBack = true;
            @__ctrl.SelectedIndexChanged -= new System.EventHandler(this.cboReunioes_SelectedIndexChanged);
            @__ctrl.SelectedIndexChanged += new System.EventHandler(this.cboReunioes_SelectedIndexChanged);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.Label @__BuildControllblErro() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            this.lblErro = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "lblErro";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control2(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.BackColor = System.Drawing.Color.White;
            @__ctrl.ForeColor = ((System.Drawing.Color)(System.Drawing.Color.FromArgb(40, 71, 117)));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control4() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            @__ctrl.DataField = "Pessoa";
            @__ctrl.HeaderText = "Nome";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control5() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            @__ctrl.DataField = "id_usuario";
            @__ctrl.HeaderText = "Login";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control3(System.Web.UI.WebControls.DataControlFieldCollection @__ctrl) {
            global::System.Web.UI.WebControls.BoundField @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control4();
            @__ctrl.Add(@__ctrl1);
            global::System.Web.UI.WebControls.BoundField @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control5();
            @__ctrl.Add(@__ctrl2);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control6(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.BackColor = ((System.Drawing.Color)(System.Drawing.Color.FromArgb(153, 153, 153)));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control7(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.BackColor = ((System.Drawing.Color)(System.Drawing.Color.FromArgb(93, 123, 157)));
            @__ctrl.Font.Bold = true;
            @__ctrl.ForeColor = System.Drawing.Color.White;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control8(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.BackColor = ((System.Drawing.Color)(System.Drawing.Color.FromArgb(93, 123, 157)));
            @__ctrl.Font.Bold = true;
            @__ctrl.ForeColor = System.Drawing.Color.White;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control9(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.BackColor = ((System.Drawing.Color)(System.Drawing.Color.FromArgb(40, 71, 117)));
            @__ctrl.ForeColor = System.Drawing.Color.White;
            @__ctrl.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Center;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control10(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.BackColor = ((System.Drawing.Color)(System.Drawing.Color.FromArgb(247, 246, 243)));
            @__ctrl.ForeColor = ((System.Drawing.Color)(System.Drawing.Color.FromArgb(51, 51, 51)));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControl__control11(System.Web.UI.WebControls.TableItemStyle @__ctrl) {
            @__ctrl.BackColor = ((System.Drawing.Color)(System.Drawing.Color.FromArgb(226, 222, 214)));
            @__ctrl.Font.Bold = true;
            @__ctrl.ForeColor = ((System.Drawing.Color)(System.Drawing.Color.FromArgb(51, 51, 51)));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdMain() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdMain = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdMain";
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100, System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CellPadding = 4;
            @__ctrl.EnableModelValidation = true;
            @__ctrl.ForeColor = ((System.Drawing.Color)(System.Drawing.Color.FromArgb(51, 51, 51)));
            this.@__BuildControl__control2(@__ctrl.AlternatingRowStyle);
            this.@__BuildControl__control3(@__ctrl.Columns);
            this.@__BuildControl__control6(@__ctrl.EditRowStyle);
            this.@__BuildControl__control7(@__ctrl.FooterStyle);
            this.@__BuildControl__control8(@__ctrl.HeaderStyle);
            this.@__BuildControl__control9(@__ctrl.PagerStyle);
            this.@__BuildControl__control10(@__ctrl.RowStyle);
            this.@__BuildControl__control11(@__ctrl.SelectedRowStyle);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::com.sandigital.sharepoint.webparts.ParticipantesReuniaoLista.ParticipantesReuniaoLista @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n<table style=\"\">\r\n    <tr>\r\n        <td style=\"\">Data da Reunião:</td>\r\n " +
                        "       <td style=\"width:10px;\"></td>\r\n        <td>"));
            global::DevExpress.Web.ASPxEditors.ASPxComboBox @__ctrl1;
            @__ctrl1 = this.@__BuildControlcboReunioes();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("</td>\r\n    </tr>\r\n\r\n</table>\r\n       \r\n<br />\r\n\r\n"));
            global::System.Web.UI.WebControls.Label @__ctrl2;
            @__ctrl2 = this.@__BuildControllblErro();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            global::System.Web.UI.WebControls.GridView @__ctrl3;
            @__ctrl3 = this.@__BuildControlgrdMain();
            @__parser.AddParsedSubObject(@__ctrl3);
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
